#!/usr/bin/env bash

verify_deps() {
    deps=('curl' 'jq')

    for dep in "${deps[@]}"; do
        command -v $dep >/dev/null 2>&1 || { echo >&2 "$dep is not installed.  Aborting."; exit 1; }
    done
}

google_term() {
    # echo $1
    curl -ssL "https://www.googleapis.com/customsearch/v1?key=${GOOGLE_API_KEY}&cx=${SEARCH_ENGINE}&q=$1" | \
	jq '.items | .[] | .title'
}

main() {
    verify_deps
    google_term "$@"
    echo 'success!'
}

main "$@"

