ZSH_THEME="kennethreitz"
# ZSH_THEME="af-magic"

COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_TITLE="true"
unsetopt correct_all

export PATH=/usr/local/opt/imagemagick@6/bin:$HOME/bin:$HOME/.npm-global/bin:/usr/local/bin:/usr/local/sbin:$HOME/.nimble/bin:$HOME/.cargo/bin:/usr/local/opt/libxml2/bin:$PATH

# export MANPATH="/usr/local/man:$MANPATH"

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig
export EDITOR=nvim
export ERL_AFLAGS="-kernel shell_history enabled"
export GPG_TTY=$(tty)
export LANG=en_US.UTF-8
export UPDATE_ZSH_DAYS=30
export ZSH="/Users/ijohnson/.oh-my-zsh"

source $ZSH/oh-my-zsh.sh

plugins=(git history)

shovel() ( cd ~/Code/dev && ./script/run shovel "$@"; )

source $HOME/.zsh_aliases

source /usr/local/share/chruby/chruby.sh
chruby 2.4.3

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# brew services start redis
# brew services start postgres

