[options]
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = true
    guifont = "FuraMono Nerd Font"
    statusline_separator = "slant"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = false

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'core#banner'

[[layers]]
name = 'core#statusline'

[[layers]]
name = 'core#tabline'

[[layers]]
name = "git"

[[layers]]
name = "colorscheme"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "tools"

[[layers]]
name = "fzf"
